version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - node -v
      - npm -v
  build:
    commands:
      - npm install
      - npm build
       
  post_build:
    commands:
      - pwd
      - ls
      
                 
#artifacts:
#  files:
#    - dist
