name: Angular Project

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 12
    - run: npm ci && npm run build && pwd && ls
    - name: Zip dist files
      id: zip
      uses: Roslovets-Inc/zip-npm-files@v1
      with:
        files: dist
    
    - name: Deploy war file
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }} 
        port: ${{ secrets.SSH_PORT }} 
        username: ${{ secrets.SSH_USER }} 
        key: ${{ secrets.SSH_KEY }} 
        files: |
            rent-acar-front-end0.0.0.zip
        remote-path: "/home/ubuntu/"
            
        
