name: Angular Project
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 12
    - run: npm ci && npm run build --prod && pwd && ls
    
    - name: Zip dist files
      id: zip
      uses: Roslovets-Inc/zip-npm-files@v1
      with:
        files: dist
    - run: pwd && ls
    
    - name: Upload an artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: artifact-file
        path: /home/runner/work/angular/angular/rent-acar-front-end0.0.0.zip
           
  deploy:      
    runs-on: ubuntu-latest    
    environment: 'prod'
    steps:   
    - name: Download artifact
      uses: actions/download-artifact@v2.1.1
      with: 
        name: artifact-file
    - name: Test SSH Connection.
      env: 
       SSH_KEY: ${{ secrets.SSH_KEY }}
       SSH_USER: ${{ secrets.SSH_USER }}
       SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
       echo "$SSH_KEY" > Private_Key && sudo chmod 600 Private_Key
       ssh -o StrictHostKeyChecking=no -i Private_Key -t ${SSH_USER}@${SSH_HOST} "sudo su; sudo systemctl stop nginx"
       scp -o StrictHostKeyChecking=no -i Private_Key rent-acar-front-end0.0.0.zip ${SSH_USER}@${SSH_HOST}:/home/ubuntu
