name: Angular Project

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.
    - uses: actions/setup-node@v3
      with:
       node-version: 12
    - run: |
       npm i
       npm run build:prod
       pwd
       ls
    
        
